// Generated by backend/app/scripts/export_frontend_constants.py (spec §11.3) — do not edit.
// Single source of truth: backend domain constants (drift-checked in CI).

export const MAX_GUEST_MESSAGE_LENGTH = 4000;
export const EMAIL_MAX_LENGTH = 254;
export const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
