/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sample/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sample-flow reply generated on the server key (§5.3, US-01). */
        post: operations["sample_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capture an email and send the magic link (§5.4, US-02). */
        post: operations["capture_lead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/magic-link/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve a magic-link token to the lead + guidebook metadata (§5.5, US-03). */
        get: operations["resolve_magic_link"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a guidebook file or rendered template text (§5.6, US-04/US-05). */
        post: operations["upload_guidebook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Real-flow reply to a guest message using the host's BYOK key (§5.7, US-06). */
        post: operations["generate_response"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SampleGenerateRequest: {
            message: string;
        };
        CaptureLeadRequest: {
            email: string;
            flow: string;
            /** @default  */
            honeypot: string;
        };
        GenerateRequest: {
            message: string;
        };
        UploadGuidebookRequest: {
            name: string;
            /** Format: binary */
            file: string;
        };
        SampleGenerateResult: {
            response_text: string;
        };
        ResolveMagicLinkResult: {
            email: string;
            flow: string;
            guidebook_id: string | null;
            guidebook_name: string | null;
            guidebook_created_at: string | null;
        };
        IngestionResult: {
            guidebook_id: string;
            name: string;
            created_at: string;
        };
        GenerateResponseResult: {
            response_text: string;
        };
        StatusSentResponse: {
            /** @enum {string} */
            status: "sent";
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error_ERR_EMAIL_CONFLICT"] | components["schemas"]["Error_ERR_EMPTY_DOCUMENT"] | components["schemas"]["Error_ERR_INTERNAL"] | components["schemas"]["Error_ERR_INVALID_API_KEY"] | components["schemas"]["Error_ERR_INVALID_MAGIC_LINK"] | components["schemas"]["Error_ERR_INVALID_PAYLOAD"] | components["schemas"]["Error_ERR_NOT_FOUND"] | components["schemas"]["Error_ERR_NO_GUIDEBOOK"] | components["schemas"]["Error_ERR_PAYLOAD_TOO_LARGE"] | components["schemas"]["Error_ERR_RATE_LIMIT"] | components["schemas"]["Error_ERR_SAMPLE_BUDGET_EXHAUSTED"] | components["schemas"]["Error_ERR_TOO_MANY_CHUNKS"] | components["schemas"]["Error_ERR_UNSUPPORTED_MEDIA_TYPE"] | components["schemas"]["Error_ERR_UPSTREAM_EMAIL"] | components["schemas"]["Error_ERR_UPSTREAM_LLM"];
        };
        Error_ERR_EMAIL_CONFLICT: {
            /** @enum {string} */
            code: "ERR_EMAIL_CONFLICT";
            message: string;
            details: Record<string, never>;
        };
        Error_ERR_EMPTY_DOCUMENT: {
            /** @enum {string} */
            code: "ERR_EMPTY_DOCUMENT";
            message: string;
            details: Record<string, never>;
        };
        Error_ERR_INTERNAL: {
            /** @enum {string} */
            code: "ERR_INTERNAL";
            message: string;
            details: {
                request_id: string;
            };
        };
        Error_ERR_INVALID_API_KEY: {
            /** @enum {string} */
            code: "ERR_INVALID_API_KEY";
            message: string;
            details: Record<string, never>;
        };
        Error_ERR_INVALID_MAGIC_LINK: {
            /** @enum {string} */
            code: "ERR_INVALID_MAGIC_LINK";
            message: string;
            details: Record<string, never>;
        };
        Error_ERR_INVALID_PAYLOAD: {
            /** @enum {string} */
            code: "ERR_INVALID_PAYLOAD";
            message: string;
            details: {
                field: string | null;
                reason: string | null;
            };
        };
        Error_ERR_NOT_FOUND: {
            /** @enum {string} */
            code: "ERR_NOT_FOUND";
            message: string;
            details: {
                resource: string;
            };
        };
        Error_ERR_NO_GUIDEBOOK: {
            /** @enum {string} */
            code: "ERR_NO_GUIDEBOOK";
            message: string;
            details: Record<string, never>;
        };
        Error_ERR_PAYLOAD_TOO_LARGE: {
            /** @enum {string} */
            code: "ERR_PAYLOAD_TOO_LARGE";
            message: string;
            details: {
                max_bytes: number;
            };
        };
        Error_ERR_RATE_LIMIT: {
            /** @enum {string} */
            code: "ERR_RATE_LIMIT";
            message: string;
            details: {
                scope: string;
                retry_after_s: number;
            };
        };
        Error_ERR_SAMPLE_BUDGET_EXHAUSTED: {
            /** @enum {string} */
            code: "ERR_SAMPLE_BUDGET_EXHAUSTED";
            message: string;
            details: {
                reset_at: string;
            };
        };
        Error_ERR_TOO_MANY_CHUNKS: {
            /** @enum {string} */
            code: "ERR_TOO_MANY_CHUNKS";
            message: string;
            details: {
                max_chunks: number;
            };
        };
        Error_ERR_UNSUPPORTED_MEDIA_TYPE: {
            /** @enum {string} */
            code: "ERR_UNSUPPORTED_MEDIA_TYPE";
            message: string;
            details: {
                allowed: string[];
            };
        };
        Error_ERR_UPSTREAM_EMAIL: {
            /** @enum {string} */
            code: "ERR_UPSTREAM_EMAIL";
            message: string;
            details: {
                retryable: boolean;
            };
        };
        Error_ERR_UPSTREAM_LLM: {
            /** @enum {string} */
            code: "ERR_UPSTREAM_LLM";
            message: string;
            details: {
                upstream_status: number | null;
                retryable: boolean;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sample_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleGenerateRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SampleGenerateResult"];
                };
            };
            /** @description Error: ERR_INVALID_PAYLOAD */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_RATE_LIMIT, ERR_SAMPLE_BUDGET_EXHAUSTED */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_INTERNAL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_UPSTREAM_LLM */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    capture_lead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureLeadRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusSentResponse"];
                };
            };
            /** @description Error: ERR_INVALID_PAYLOAD */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_RATE_LIMIT */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_INTERNAL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_UPSTREAM_EMAIL */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    resolve_magic_link: {
        parameters: {
            query?: never;
            header: {
                "X-Magic-Link": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveMagicLinkResult"];
                };
            };
            /** @description Error: ERR_INVALID_MAGIC_LINK */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_RATE_LIMIT */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_INTERNAL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    upload_guidebook: {
        parameters: {
            query?: never;
            header: {
                "X-Magic-Link": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadGuidebookRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResult"];
                };
            };
            /** @description Error: ERR_INVALID_MAGIC_LINK */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_PAYLOAD_TOO_LARGE, ERR_TOO_MANY_CHUNKS */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_UNSUPPORTED_MEDIA_TYPE */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_EMPTY_DOCUMENT, ERR_INVALID_PAYLOAD */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_RATE_LIMIT */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_INTERNAL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    generate_response: {
        parameters: {
            query?: never;
            header: {
                "X-Magic-Link": string;
                "X-Api-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Success. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponseResult"];
                };
            };
            /** @description Error: ERR_INVALID_MAGIC_LINK, ERR_INVALID_API_KEY */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_NO_GUIDEBOOK */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_INVALID_PAYLOAD */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_RATE_LIMIT */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_INTERNAL */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Error: ERR_UPSTREAM_LLM */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
