"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-20
"""

from __future__ import annotations

from alembic import op

from infrastructure.db.sqlalchemy.schema import metadata

revision: str = "0001"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Materialise the single-source-of-truth schema (infrastructure/db/schema.py) — tables,
    # constraints and the §4.6 partial indexes. Future schema changes are emitted as autogenerated
    # diff migrations against the same metadata (env.py target_metadata).
    metadata.create_all(op.get_bind())


def downgrade() -> None:
    metadata.drop_all(op.get_bind())
