"""Toolchain version drift guard (spec §13 / CI).

`.tool-versions` is the single source of truth for python / poetry / nodejs / terraform. Each tool reads
its OWN manifest (pyproject, package.json, versions.tf, the Dockerfile, the lockfile), so the versions
cannot be one literal — instead this guard fails if any manifest disagrees with `.tool-versions`.

Run via `make check-versions`; exits non-zero (with the mismatches) on drift, zero when consistent.
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
# Component roots in the monorepo: the lead-capture backend, the Holahost frontend, and the Holahost
# platform infra. `.tool-versions` stays at the repo root (single source, shared).
_BACKEND = _ROOT / "holahost" / "services" / "lead-capture" / "backend"
_FRONTEND = _ROOT / "holahost" / "frontend"
_INFRA = _ROOT / "holahost" / "infra"


def _tool_versions() -> dict[str, str]:
    out: dict[str, str] = {}
    for raw in (_ROOT / ".tool-versions").read_text().splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            tool, version = line.split()[:2]
            out[tool] = version
    return out


def main() -> int:
    tv = _tool_versions()
    py, poetry_v, node, tf = tv["python"], tv["poetry"], tv["nodejs"], tv["terraform"]
    errors: list[str] = []

    pyproject = tomllib.loads((_BACKEND / "pyproject.toml").read_text())
    requires_python = pyproject["project"]["requires-python"]
    if py not in requires_python:
        errors.append(f"pyproject requires-python '{requires_python}' lacks {py}")
    ruff_target = pyproject["tool"]["ruff"]["target-version"]
    if ruff_target != f"py{py.replace('.', '')}":
        errors.append(f"pyproject ruff target-version '{ruff_target}' != py{py.replace('.', '')}")
    mypy_py = pyproject["tool"]["mypy"]["python_version"]
    if mypy_py != py:
        errors.append(f"pyproject mypy python_version '{mypy_py}' != {py}")

    dockerfile = (_BACKEND / "Dockerfile").read_text()
    m = re.search(r"ARG PYTHON_VERSION=(\S+)", dockerfile)
    if not m or m.group(1) != py:
        errors.append(f"Dockerfile ARG PYTHON_VERSION '{m.group(1) if m else '?'}' != {py}")

    lock_head = (_BACKEND / "poetry.lock").read_text().splitlines()[0]
    m = re.search(r"generated by Poetry (\S+)", lock_head)
    if not m or m.group(1) != poetry_v:
        errors.append(f"poetry.lock generated by '{m.group(1) if m else '?'}' != {poetry_v}")

    pkg = json.loads((_FRONTEND / "package.json").read_text())
    node_engine = str(pkg.get("engines", {}).get("node", ""))
    if node not in node_engine:
        errors.append(f"package.json engines.node '{node_engine}' lacks {node}")

    for root in ("common", "staging/capture-lead", "staging/gateway"):
        versions_tf = (_INFRA / "envs" / root / "versions.tf").read_text()
        m = re.search(r'required_version\s*=\s*"([^"]+)"', versions_tf)
        if not m or tf not in m.group(1):
            errors.append(f"holahost/infra/envs/{root}/versions.tf required_version lacks {tf}")

    if errors:
        print("Version drift vs .tool-versions:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    print(f"versions OK: python {py}, poetry {poetry_v}, nodejs {node}, terraform {tf}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
