"""Export domain constants the frontend re-uses to ``frontend/src/api/constants.generated.ts`` (§11.3).

Single source of truth for the FE-side validation values (ticket F-05): they are imported from the
backend domain, so they cannot drift. Run ``make -C backend export-frontend-constants``; the CI drift
guard is ``make -C backend check-frontend-constants``.

The email regex is translated from Python to JS syntax (``\\A`` -> ``^``, ``\\Z`` -> ``$``); the export
fails fast if the pattern uses Python-only regex constructs that have no direct JS equivalent.
"""

from __future__ import annotations

from pathlib import Path

from domain.entities.guest_message import MAX_GUEST_MESSAGE_LENGTH
from domain.value_objects.email import EMAIL_MAX_LENGTH, EMAIL_REGEX

# This file: holahost/services/lead-capture/backend/app/scripts/export_frontend_constants.py.
# parents[3] == the lead-capture service root; parents[5] == the Holahost app root, which owns frontend/.
_OUTPUT_PATH = (
    Path(__file__).resolve().parents[5] / "frontend" / "src" / "api" / "constants.generated.ts"
)

# Python regex constructs with no direct JS equivalent (checked after the \A/\Z anchor translation).
_PY_ONLY_REGEX = ("(?P<", "(?P=", "(?#")


def _to_js_regex(pattern: str) -> str:
    """Translate a simple Python regex pattern to JS syntax.

    :raises ValueError: if the pattern uses Python-only constructs unsupported in a JS RegExp literal.
    """
    js = pattern.replace("\\A", "^").replace("\\Z", "$")
    bad = [tok for tok in _PY_ONLY_REGEX if tok in js]
    if bad:
        raise ValueError(f"EMAIL_REGEX uses Python-only regex constructs unsupported in JS: {bad}")
    if "/" in js:
        raise ValueError("EMAIL_REGEX contains '/'; emit via new RegExp(...) instead of a literal")
    return js


def _render() -> str:
    """Render the generated TypeScript module."""
    email_js = _to_js_regex(EMAIL_REGEX.pattern)
    return (
        "// Generated by backend/app/scripts/export_frontend_constants.py (spec §11.3) — do not edit.\n"
        "// Single source of truth: backend domain constants (drift-checked in CI).\n"
        "\n"
        f"export const MAX_GUEST_MESSAGE_LENGTH = {MAX_GUEST_MESSAGE_LENGTH};\n"
        f"export const EMAIL_MAX_LENGTH = {EMAIL_MAX_LENGTH};\n"
        f"export const EMAIL_REGEX = /{email_js}/;\n"
    )


def main() -> None:
    """Write the generated constants module to the frontend."""
    _OUTPUT_PATH.write_text(_render(), encoding="utf-8")
    print(f"wrote {_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
